created(1622939632.527819).
assert(bookmark(3,"UFG","www.ufg.br")).
assert(bookmark(11,"Exemplo","https://exemplo.br/")).
assert(bookmark(4,"UFRJ","https://ufrj.br")).
assert(bookmark(13,"Livro","http://book.com.br")).
assert(bookmark(12,"Lanchonete","https://lanchonete.br/")).
assert(bookmark(14,"ufu","http://www.ufu.br")).
assert(bookmark(15,"ufu","http://www.ufu.br")).
assert(bookmark(16,"ufu","http://www.ufu.br")).
